language: go
go:
  - 1.8.x
  - 1.9.x
  - nightly
install:
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - GLIDE_TAG=v0.12.3
  - GLIDE_DOWNLOAD="https://github.com/Masterminds/glide/releases/download/$GLIDE_TAG/glide-$GLIDE_TAG-linux-amd64.tar.gz"
  - curl -L $GLIDE_DOWNLOAD | tar -xvz
  - export PATH=$PATH:$PWD/linux-amd64/
  - glide install
  - ./goclean.sh
