language: go
go:
  - 1.8.x
  - 1.9.x
  - nightly
install:
  - go get -v github.com/alecthomas/gometalinter
  - gometalinter --install
  - curl https://glide.sh/get | sh
  - mkdir -p coverage/

script:
  - glide install
  - make test
  - ./goclean.sh
