// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/protobuf/payments/payments.proto

/*
Package payments is a generated protocol buffer package.

It is generated from these files:
	pkg/protobuf/payments/payments.proto

It has these top-level messages:
	Output
	PaymentDetails
	PaymentRequest
	X509Certificates
	Payment
	PaymentACK
*/
package payments

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Generalized form of "send payment to this/these bitcoin addresses"
type Output struct {
	Amount           *uint64 `protobuf:"varint,1,opt,name=amount,def=0" json:"amount,omitempty"`
	Script           []byte  `protobuf:"bytes,2,req,name=script" json:"script,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Output) Reset()                    { *m = Output{} }
func (m *Output) String() string            { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()               {}
func (*Output) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Output_Amount uint64 = 0

func (m *Output) GetAmount() uint64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return Default_Output_Amount
}

func (m *Output) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type PaymentDetails struct {
	Network          *string   `protobuf:"bytes,1,opt,name=network,def=main" json:"network,omitempty"`
	Outputs          []*Output `protobuf:"bytes,2,rep,name=outputs" json:"outputs,omitempty"`
	Time             *uint64   `protobuf:"varint,3,req,name=time" json:"time,omitempty"`
	Expires          *uint64   `protobuf:"varint,4,opt,name=expires" json:"expires,omitempty"`
	Memo             *string   `protobuf:"bytes,5,opt,name=memo" json:"memo,omitempty"`
	PaymentUrl       *string   `protobuf:"bytes,6,opt,name=payment_url,json=paymentUrl" json:"payment_url,omitempty"`
	MerchantData     []byte    `protobuf:"bytes,7,opt,name=merchant_data,json=merchantData" json:"merchant_data,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *PaymentDetails) Reset()                    { *m = PaymentDetails{} }
func (m *PaymentDetails) String() string            { return proto.CompactTextString(m) }
func (*PaymentDetails) ProtoMessage()               {}
func (*PaymentDetails) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_PaymentDetails_Network string = "main"

func (m *PaymentDetails) GetNetwork() string {
	if m != nil && m.Network != nil {
		return *m.Network
	}
	return Default_PaymentDetails_Network
}

func (m *PaymentDetails) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *PaymentDetails) GetTime() uint64 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *PaymentDetails) GetExpires() uint64 {
	if m != nil && m.Expires != nil {
		return *m.Expires
	}
	return 0
}

func (m *PaymentDetails) GetMemo() string {
	if m != nil && m.Memo != nil {
		return *m.Memo
	}
	return ""
}

func (m *PaymentDetails) GetPaymentUrl() string {
	if m != nil && m.PaymentUrl != nil {
		return *m.PaymentUrl
	}
	return ""
}

func (m *PaymentDetails) GetMerchantData() []byte {
	if m != nil {
		return m.MerchantData
	}
	return nil
}

type PaymentRequest struct {
	PaymentDetailsVersion    *uint32 `protobuf:"varint,1,opt,name=payment_details_version,json=paymentDetailsVersion,def=1" json:"payment_details_version,omitempty"`
	PkiType                  *string `protobuf:"bytes,2,opt,name=pki_type,json=pkiType,def=none" json:"pki_type,omitempty"`
	PkiData                  []byte  `protobuf:"bytes,3,opt,name=pki_data,json=pkiData" json:"pki_data,omitempty"`
	SerializedPaymentDetails []byte  `protobuf:"bytes,4,req,name=serialized_payment_details,json=serializedPaymentDetails" json:"serialized_payment_details,omitempty"`
	Signature                []byte  `protobuf:"bytes,5,opt,name=signature" json:"signature,omitempty"`
	XXX_unrecognized         []byte  `json:"-"`
}

func (m *PaymentRequest) Reset()                    { *m = PaymentRequest{} }
func (m *PaymentRequest) String() string            { return proto.CompactTextString(m) }
func (*PaymentRequest) ProtoMessage()               {}
func (*PaymentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

const Default_PaymentRequest_PaymentDetailsVersion uint32 = 1
const Default_PaymentRequest_PkiType string = "none"

func (m *PaymentRequest) GetPaymentDetailsVersion() uint32 {
	if m != nil && m.PaymentDetailsVersion != nil {
		return *m.PaymentDetailsVersion
	}
	return Default_PaymentRequest_PaymentDetailsVersion
}

func (m *PaymentRequest) GetPkiType() string {
	if m != nil && m.PkiType != nil {
		return *m.PkiType
	}
	return Default_PaymentRequest_PkiType
}

func (m *PaymentRequest) GetPkiData() []byte {
	if m != nil {
		return m.PkiData
	}
	return nil
}

func (m *PaymentRequest) GetSerializedPaymentDetails() []byte {
	if m != nil {
		return m.SerializedPaymentDetails
	}
	return nil
}

func (m *PaymentRequest) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

type X509Certificates struct {
	Certificate      [][]byte `protobuf:"bytes,1,rep,name=certificate" json:"certificate,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *X509Certificates) Reset()                    { *m = X509Certificates{} }
func (m *X509Certificates) String() string            { return proto.CompactTextString(m) }
func (*X509Certificates) ProtoMessage()               {}
func (*X509Certificates) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *X509Certificates) GetCertificate() [][]byte {
	if m != nil {
		return m.Certificate
	}
	return nil
}

type Payment struct {
	MerchantData     []byte    `protobuf:"bytes,1,opt,name=merchant_data,json=merchantData" json:"merchant_data,omitempty"`
	Transactions     [][]byte  `protobuf:"bytes,2,rep,name=transactions" json:"transactions,omitempty"`
	RefundTo         []*Output `protobuf:"bytes,3,rep,name=refund_to,json=refundTo" json:"refund_to,omitempty"`
	Memo             *string   `protobuf:"bytes,4,opt,name=memo" json:"memo,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Payment) Reset()                    { *m = Payment{} }
func (m *Payment) String() string            { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()               {}
func (*Payment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Payment) GetMerchantData() []byte {
	if m != nil {
		return m.MerchantData
	}
	return nil
}

func (m *Payment) GetTransactions() [][]byte {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *Payment) GetRefundTo() []*Output {
	if m != nil {
		return m.RefundTo
	}
	return nil
}

func (m *Payment) GetMemo() string {
	if m != nil && m.Memo != nil {
		return *m.Memo
	}
	return ""
}

type PaymentACK struct {
	Payment          *Payment `protobuf:"bytes,1,req,name=payment" json:"payment,omitempty"`
	Memo             *string  `protobuf:"bytes,2,opt,name=memo" json:"memo,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PaymentACK) Reset()                    { *m = PaymentACK{} }
func (m *PaymentACK) String() string            { return proto.CompactTextString(m) }
func (*PaymentACK) ProtoMessage()               {}
func (*PaymentACK) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PaymentACK) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

func (m *PaymentACK) GetMemo() string {
	if m != nil && m.Memo != nil {
		return *m.Memo
	}
	return ""
}

func init() {
	proto.RegisterType((*Output)(nil), "payments.Output")
	proto.RegisterType((*PaymentDetails)(nil), "payments.PaymentDetails")
	proto.RegisterType((*PaymentRequest)(nil), "payments.PaymentRequest")
	proto.RegisterType((*X509Certificates)(nil), "payments.X509Certificates")
	proto.RegisterType((*Payment)(nil), "payments.Payment")
	proto.RegisterType((*PaymentACK)(nil), "payments.PaymentACK")
}

func init() { proto.RegisterFile("pkg/protobuf/payments/payments.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0x95, 0x1d, 0x7f, 0x71, 0x32, 0x71, 0x3f, 0x95, 0x95, 0x80, 0x2d, 0x42, 0xad, 0x65, 0x38,
	0x58, 0x20, 0xd2, 0x52, 0xc1, 0xa1, 0x81, 0x0b, 0x6d, 0x6f, 0x08, 0x51, 0xad, 0x0a, 0xe2, 0x66,
	0x6d, 0x9d, 0x4d, 0x58, 0x25, 0xde, 0x35, 0xbb, 0x63, 0x20, 0xfc, 0x0f, 0x7e, 0x21, 0xfc, 0x10,
	0xe4, 0xb5, 0x1d, 0xd3, 0x56, 0xdc, 0x66, 0xde, 0x3c, 0xbf, 0x79, 0x33, 0xb3, 0x86, 0xc7, 0xe5,
	0x6a, 0x79, 0x58, 0x1a, 0x8d, 0xfa, 0xaa, 0x5a, 0x1c, 0x96, 0x7c, 0x53, 0x08, 0x85, 0x76, 0x1b,
	0x4c, 0x5d, 0x89, 0x8c, 0xba, 0x3c, 0x79, 0x05, 0xc3, 0xf7, 0x15, 0x96, 0x15, 0x92, 0x3d, 0x18,
	0xf2, 0x42, 0x57, 0x0a, 0xa9, 0x17, 0x7b, 0x69, 0x30, 0xf3, 0x8e, 0x58, 0x0b, 0x90, 0x7b, 0x30,
	0xb4, 0xb9, 0x91, 0x25, 0x52, 0x3f, 0xf6, 0xd3, 0x88, 0xb5, 0x59, 0xf2, 0xdb, 0x83, 0xff, 0x2f,
	0x1a, 0xa5, 0x73, 0x81, 0x5c, 0xae, 0x2d, 0xd9, 0x87, 0x50, 0x09, 0xfc, 0xa6, 0xcd, 0xca, 0xc9,
	0x8c, 0x67, 0x41, 0xc1, 0xa5, 0x62, 0x1d, 0x48, 0x9e, 0x40, 0xa8, 0x5d, 0x3f, 0x4b, 0xfd, 0x78,
	0x90, 0x4e, 0x8e, 0x77, 0xa7, 0x5b, 0x6f, 0x8d, 0x11, 0xd6, 0x11, 0x08, 0x81, 0x00, 0x65, 0x21,
	0xe8, 0x20, 0xf6, 0xd3, 0x80, 0xb9, 0x98, 0x50, 0x08, 0xc5, 0xf7, 0x52, 0x1a, 0x61, 0x69, 0x50,
	0xdb, 0x64, 0x5d, 0x5a, 0xb3, 0x0b, 0x51, 0x68, 0xfa, 0x5f, 0xdd, 0x96, 0xb9, 0x98, 0x1c, 0xc0,
	0xa4, 0x55, 0xcf, 0x2a, 0xb3, 0xa6, 0x43, 0x57, 0x82, 0x16, 0xfa, 0x60, 0xd6, 0xe4, 0x11, 0xec,
	0x14, 0xc2, 0xe4, 0x9f, 0xb9, 0xc2, 0x6c, 0xce, 0x91, 0xd3, 0x30, 0xf6, 0xd2, 0x88, 0x45, 0x1d,
	0x78, 0xce, 0x91, 0x27, 0xbf, 0xfa, 0x31, 0x99, 0xf8, 0x52, 0x09, 0x8b, 0xe4, 0x04, 0xee, 0x77,
	0xc2, 0xf3, 0x66, 0xf2, 0xec, 0xab, 0x30, 0x56, 0x6a, 0xe5, 0xc6, 0xde, 0x99, 0x79, 0xcf, 0xd9,
	0xdd, 0xf2, 0xda, 0x6a, 0x3e, 0x36, 0x75, 0x72, 0x00, 0xa3, 0x72, 0x25, 0x33, 0xdc, 0x94, 0x82,
	0xfa, 0xcd, 0x8a, 0x94, 0x56, 0x82, 0x85, 0xe5, 0x4a, 0x5e, 0x6e, 0x4a, 0x41, 0xf6, 0x1a, 0x82,
	0xb3, 0x33, 0x70, 0x76, 0xea, 0x52, 0xed, 0x84, 0xbc, 0x86, 0x07, 0x56, 0x18, 0xc9, 0xd7, 0xf2,
	0x87, 0x98, 0x67, 0x37, 0x1c, 0xd0, 0xc0, 0x1d, 0x87, 0xf6, 0x8c, 0x1b, 0xb7, 0x79, 0x08, 0x63,
	0x2b, 0x97, 0x8a, 0x63, 0x65, 0x84, 0x5b, 0x53, 0xc4, 0x7a, 0x20, 0x79, 0x01, 0xbb, 0x9f, 0x5e,
	0x1e, 0x9d, 0x9c, 0x09, 0x83, 0x72, 0x21, 0x73, 0x8e, 0xc2, 0x92, 0x18, 0x26, 0x79, 0x9f, 0x53,
	0x2f, 0x1e, 0xa4, 0x11, 0xfb, 0x1b, 0x4a, 0x7e, 0x7a, 0x10, 0xb6, 0x6d, 0x6e, 0x2f, 0xd3, 0xbb,
	0xbd, 0x4c, 0x92, 0x40, 0x84, 0x86, 0x2b, 0xcb, 0x73, 0x94, 0x5a, 0x35, 0xaf, 0x20, 0x62, 0xd7,
	0x30, 0xf2, 0x0c, 0xc6, 0x46, 0x2c, 0x2a, 0x35, 0xcf, 0x50, 0xd3, 0xc1, 0x3f, 0x9e, 0xc9, 0xa8,
	0xa1, 0x5c, 0xea, 0xed, 0xe5, 0x83, 0xfe, 0xf2, 0xc9, 0x3b, 0x80, 0xd6, 0xd6, 0x9b, 0xb3, 0xb7,
	0xe4, 0x29, 0x84, 0xed, 0xe7, 0xd4, 0x8b, 0xfd, 0x74, 0x72, 0x7c, 0xa7, 0x97, 0xeb, 0x2e, 0xdb,
	0x31, 0xb6, 0x72, 0x7e, 0x2f, 0x77, 0x9a, 0xc2, 0xbe, 0x36, 0xcb, 0xe9, 0x95, 0xc4, 0x5c, 0x4b,
	0xd5, 0xfc, 0x45, 0xb9, 0x5e, 0xdb, 0xad, 0xcc, 0xe9, 0xf0, 0xa2, 0xc6, 0xec, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x93, 0xc9, 0x02, 0x75, 0x81, 0x03, 0x00, 0x00,
}
